[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  
# Environment variables for build
[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"
  
# Build processing settings
[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://js.sparkloop.app https://script.sparkloop.app https://js.stripe.com https://connect.facebook.net https://sdks.shopifycdn.com; style-src 'self' 'unsafe-inline' https://dash.sparkloop.app https://fonts.googleapis.com; img-src 'self' data: https:; font-src 'self' https://fonts.gstatic.com; media-src 'self' https://cdn.shopify.com; connect-src 'self' https://api.supabase.io https://*.supabase.co https://js.sparkloop.app https://script.sparkloop.app https://script-settings.sparkloop.app https://sparkloop.app https://*.sparkloop.app https://magma-agency.app.n8n.cloud https://api.beehiiv.com https://api.stripe.com https://checkout.stripe.com https://www.facebook.com https://graph.facebook.com https://*.myshopify.com https://monorail-edge.shopifysvc.com; frame-src 'self' https://sparkloop.app https://*.sparkloop.app https://checkout.stripe.com https://js.stripe.com https://*.myshopify.com;"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
[[headers]]
  for = "*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "*.woff2"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Auth route redirects
[[redirects]]
  from = "/login"
  to = "/admin/login"
  status = 200

[[redirects]]
  from = "/signin"
  to = "/admin/login"
  status = 200


[[redirects]]
  from = "/auth/*"
  to = "/admin/login"
  status = 200

# Admin redirects
[[redirects]]
  from = "/admin"
  to = "/admin/dashboard"
  status = 200

# Blog route redirects
[[redirects]]
  from = "/blog"
  to = "/blog/index"
  status = 200

[[redirects]]
  from = "/post/*"
  to = "/blog/:splat"
  status = 200

[[redirects]]
  from = "/category/*"
  to = "/categories/:splat"
  status = 200

# API function redirects
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# SPA fallback - must be last
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
