export { ShiftHowItWorks } from './ShiftHowItWorks'
export { ShiftEducational } from './ShiftEducational'
export { ShiftTestimonials } from './ShiftTestimonials'
export { ShiftBonusOffer } from './ShiftBonusOffer'
export { ShiftHighlights } from './ShiftHighlights'
