export { ProductHero } from './ProductHero'
export { SocialProofStats } from './SocialProofStats'
export { FAQSection } from './FAQSection'
export { FinalCTA } from './FinalCTA'
export { ReviewsSection } from './ReviewsSection'
export { ProductDetailsTabbed } from './ProductDetailsTabbed'
